export { HomePageMan } from "./Home/Home";
export { StudentPage } from "./StudentsPage/StudentsPage";
export { TeachersPage } from "./TeachersPage/TeachersPage";
export { RoomsPage } from "./Rooms/Rooms";
export { Attendance } from "./Attendance/Attendance";
export { AttendanceSingle } from "./AttendanceSingle/AttendanceSingle";
export { RoomSingle } from "./RoomSingle/RoomSingle";
export { TypeSingle } from "./TypeSingle/TypeSingle";
export { TableTypeSingle } from "./TableTypeSingle/TableTypeSingle";
